AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Secrets Manager Page

Parameters:
  ApplicationName:
    Type: String
    Default: 'ServerlessSecretsManagerPage'
  FrontPageApiStageName:
    Type: String
    Default: 'ProdStage'

Resources:
  FrontPageApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServerlessSecretsManagerPageApi
      EndpointConfiguration: REGIONAL
      StageName: !Ref FrontPageApiStageName

  FrontPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - arm64
      FunctionName: ServerlessSecretsManagerPageFrontFunction
      CodeUri: bin/
      Handler: bootstrap
      MemorySize: 256
      Runtime: provided.al2
      Description: 'SecretsManager Front Function'
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          API_PATH: !Join [ '', [ '/', !Ref FrontPageApiStageName, '/api'] ]
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/'
            Method: get
            RestApiId: !Ref FrontPageApi

  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - arm64
      FunctionName: ServerlessSecretsManagerPageMainFunction
      CodeUri: api/bin/
      Handler: bootstrap
      MemorySize: 256
      Runtime: provided.al2
      Description: 'SecretsManager API Function'
      Policies:
      - Statement:
        - Effect: 'Allow'
          Action:
            - 'secretsmanager:GetSecretValue'
          Resource: '*'
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          SECRET_ID: !Ref SampleSecret
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/api'
            Method: post
            RestApiId: !Ref FrontPageApi

  SampleSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        GenerateStringKey: password
        PasswordLength: 32
        SecretStringTemplate: '{}'
        IncludeSpace: false
        ExcludeLowercase: false
        ExcludeUppercase: false
        ExcludeNumbers: false
        ExcludePunctuation: true

Outputs:
  APIURI:
    Description: "URI"
    Value: !Join [ '', [ 'https://', !Ref FrontPageApi, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref FrontPageApiStageName,'/'] ]
  GetSecretValueByCLI:
    Description: "SecretValue"
    Value: !Sub |+
        aws secretsmanager get-secret-value
          --secret-id ${SampleSecret}
          --region ${AWS::Region}
          --query SecretString
